//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7eam_Sondeo_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.sondeo = new HashSet<sondeo>();
        }
    
        public string id_producto { get; set; }
        public string id_categoria { get; set; }
        public string unidad_medida { get; set; }
        public string id_marca { get; set; }
        public string nombre { get; set; }
        public string presentacion { get; set; }
        public decimal precio_consulta { get; set; }
        public string tipo { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual marca marca { get; set; }
        public virtual medida medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sondeo> sondeo { get; set; }
    }
}
