//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7eam_Sondeo_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte
    {
        public string id_reporte { get; set; }
        public string id_sondeo { get; set; }
        public string id_usuario { get; set; }
        public System.DateTime fecha_reporte { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual sondeo sondeo { get; set; }
    }
}
