//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7eam_Sondeo_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sondeo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sondeo()
        {
            this.reporte = new HashSet<reporte>();
        }
    
        public string id_sondeo { get; set; }
        public string id_municipio { get; set; }
        public string id_producto { get; set; }
        public System.DateTime fecha { get; set; }
        public string local { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporte> reporte { get; set; }
    }
}
